### ISSUE TITLE
Example for first-code-block is not clear

### ISSUE THREAD

**Issue by JJ** [antoniogamiz/Pod-Utilities#8]
It would be better if it was an actual Code block marked as such. Or if there was a list, so that it returns the first.

**Comment by antoniogamiz** [comment]
If you use indentation it is interpreted as a Pod::Block::Code.

~~~perl6
use v6.c;

say $=pod[0].contents[0] ~~ Pod::Block::Code; # True

=begin pod
    say "this is a Pod::Block::Code";
=end pod
~~~

**Comment by JJ** [comment]
Ah, right, sorry. Could be clearer, anyway...

**Comment by antoniogamiz** [comment]
Adding `=begin code =end code` is enough?

**Comment by JJ** [comment]
Yep, good idea.
